### ISSUE TITLE
fixed-name $logfile in $logpath ?

### ISSUE THREAD

**Issue by rustytravis** [IZ7BOJ/direwolf_webstat#4]
Greetings, my direwolf logfile is consistently named "/home/repeater/direwolf.log".

I edited config.php:
$logpath = "/home/repeater/";

... but can't find how to consistently state a fixed $logfile name, which results in errors.

Would this constitute a feature request, please?

**Comment by IZ7BOJ** [comment]
Dear Travis,
thanks for the interest in my dashboard.
As far as I know, direwolf creates log files in this standard format:
"Year-month-day.log" .
Every day a log file is created at 00:00 and then closed at 23:59, for that
reason I left to the user only the possibility to change the path, not the
filename.
Anyway, it's not hard to implement your modification, but I don't think to
merge it in my github. If you want, I can send you the modified files by
mail
Bests,
Alfredo


Il giorno sab 19 ago 2023 alle ore 01:27 rustytravis <
***@***.***> ha scritto:

**Comment by rustytravis** [comment]
On 8/19/23 09:29, Alfredo Vania - IZ7BOJ wrote:
> As far as I know, direwolf creates log files in this standard format:
> "Year-month-day.log" .
> Every day a log file is created at 00:00 and then closed at 23:59, for 
> that
> reason I left to the user only the possibility to change the path, not 
> the
> filename.

Many of us in emergency services prefer a single logfile for subsequent 
analyses, by stating the logfile on the startup, e.g.:

direwolf -L direwolf.log -T %H:%M:%S -t 0

**Comment by IZ7BOJ** [comment]
Uh, thank you for pointing that, I didn't know about this option.
I implemented the feature that you requested.
I added the variable $filename in config.php. If it's left empty (""), tha standard Y-m-d.log file will be used, otherwise the custom file will be considered.
Please could you try the new version and let me know if it works correctly also for you?
After this double check, I'll close the issue.
73's
Alfredo IZ7BOJ

**Comment by rustytravis** [comment]
While the $logfile is correctly addressed on the summary.php page, the live.php page does not update as packets are received, despite starting a new "Watch AX.25  realtime traffic" page. Apparently the replacement live.php didn't get updated, as the current version states:
...
if (isset($_GET['ajax'])) {
        session_start();
        $handle = fopen($logpath.date("Y-m-d").".log", 'r'); //open log
...

Thank you for your considerations.

**Comment by IZ7BOJ** [comment]
Hi Travis,
can you download the latest live.php from github and try it? It should work now..
Let me know
73's
Alfredo

**Comment by rustytravis** [comment]
It seems to work very well now, and again, thank you for an excellent body of code.

**Comment by rustytravis** [comment]
However, the issue remains in frames.php:
![image](https://github.com/IZ7BOJ/direwolf_webstat/assets/80128433/aafc1952-3c30-4433-9d3d-96049e13e5de)
$ cat -n frames.php
...
    82                  $logfile = file($logpath.gmdate("Y-m-d").".log"); //read log file
    83                  $header = str_getcsv($logfile[0]); // take header from first row
...
    93                          $linesinlog = count($logfile);
...

**Comment by IZ7BOJ** [comment]
just fixed, you can try ;-)

**Comment by rustytravis** [comment]
Seems to work perfectly, again I thank you.
